name: Tests

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "pypy2.7", "pypy3.9"]
        include:
          - setup-python: true
          - check-types: true
          - python-version: "2.7"
            container: "python:2.7.18-slim"
            setup-python: false
            check-types: false
          - python-version: "3.5"
            container: "python:3.5.10-slim"
            setup-python: false
            check-types: false
          - python-version: "3.6"
            container: "python:3.6.15-slim"
            setup-python: false
          - python-version: "3.7"
            container: "python:3.7.17-slim"
            setup-python: false
          - python-version: "pypy2.7"
            check-types: false

    runs-on: ubuntu-24.04
    container: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ matrix.setup-python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install mypy
      if: ${{ matrix.check-types }}
      run: python -m pip install mypy

    - name: Check Types
      if: ${{ matrix.check-types }}
      run: mypy periphery

    - name: Run tests
      run: |
        python -m tests.test_gpio
        python -m tests.test_gpio_sysfs
        python -m tests.test_spi
        python -m tests.test_i2c
        python -m tests.test_mmio
        python -m tests.test_serial
        python -m tests.test_led
        python -m tests.test_pwm
