name: Tests

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        container: ["python:2.7-slim", "python:3.5-slim", "python:3.6-slim", "python:3.7-slim",
                    "python:3.8-slim", "python:3.9-slim", "python:3.10-slim", "python:3.11-slim",
                    "python:3.12-slim", "python:3.13-slim", "pypy:2.7-slim", "pypy:3.11-slim"]
        include:
          - check-types: true
          - container: "python:2.7-slim"
            check-types: false
          - container: "python:3.5-slim"
            check-types: false
          - container: "pypy:2.7-slim"
            check-types: false

    runs-on: ubuntu-24.04
    container: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v4

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install mypy
      if: ${{ matrix.check-types }}
      run: python -m pip install mypy

    - name: Check Types
      if: ${{ matrix.check-types }}
      run: mypy periphery

    - name: Run tests
      run: |
        python --version
        python -m tests.test_gpio
        python -m tests.test_gpio_sysfs
        python -m tests.test_spi
        python -m tests.test_i2c
        python -m tests.test_mmio
        python -m tests.test_serial
        python -m tests.test_led
        python -m tests.test_pwm
